[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
name = "frontend"
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.8", features = ["csr", "nightly"] }
wasm-bindgen = "=0.2.102"
