[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { workspace = true, features = ["nightly"] }
serde = { workspace = true }

[features]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
